### ISSUE TITLE
Form validation errors on Sign Up and Login pages

### ISSUE THREAD

**Issue by adamnieto** [Buuntu/fastapi-react#100]
I found a bug where the frontend errors out when you press the submit button on empty fields for the login and sign up pages. 

Here is a gif of the error for the sign up page. The same error occurred with login page as well.

![error_with_signup_and_signin](https://user-images.githubusercontent.com/13468204/89610181-e2594400-d847-11ea-85c6-e04dfd52c126.gif)

**Comment by Buuntu** [comment]
Yep, thanks for reporting and you're right that this should be fixed.  Will accept a PR as long as the frontend code is "Prettified".

**Comment by adamnieto** [comment]
Here is a prettified fix: #101
