### ISSUE TITLE
click doesn't work on Frontend

### ISSUE THREAD

**Issue by psschand16** [Buuntu/fastapi-react#186]
followed the deployment procedure.
I am unable to click hyperlink on the homepage , not even able to click button using for login .
I tried different browsers.

**Comment by lach-g** [comment]
I'm having the same issue, if you did manage to solve it would you mind sharing how?
Thank you

**Comment by psschand16** [comment]
@lach-g check this https://github.com/Buuntu/fastapi-react/issues/177

it's basically incorrect typescript version. 
cheers 🍻
