### ISSUE TITLE
Love Your Project

### ISSUE THREAD

**Issue by jimwill2099** [Buuntu/fastapi-react#20]
Hi there, 

I have just gone through your portfolio on github, and I really like the whole thing! I am just wondering if you would like to let your portfolio be viewed by the world's top 5% of the developers, or seek for some advice to improve your current work. We are Skillsme, a startup founded by a group of enthusiasm coders. And we are a platform where you can post your portfolios to get endorsed and rated by the top 5% of the developers. While it is totally free for all users, only the developers we invited can post their own work without limitation. Posting your work on Skillsme is very easy. All you need is just a Github url for your public repo. Currently, we already have over 1000 users registered since our launch on March, and we are still seeking for more portfolios to join our platform. I think your portfolio has some decent stuff. So I would like to invite you to join our platform. 

Currently only the invited user can post their own portfolio on Skillsme. The invitation code for you to join and post your work is below: 
**_18f3f0f09b3a11ea911217bda66a113a_**

If you are interested, please go to https://beta.skillsme.co.nz/sessions/signup and sign up with the invitation code provided. If you want to learn more about us, please go to our website: https://www.skillsme.co.nz 

Sincerely
Skillsme Team

**Comment by w3bdesign** [comment]
This guy seems to be spamming this message all over Github, please report him.
