### ISSUE TITLE
Front end does  not respond to mouse.

### ISSUE THREAD

**Issue by ddcroft73** [Buuntu/fastapi-react#204]
The only way to navigate the front end is with the tab key. Not a frontend guy but I'm not seeing any errors. A lot of npm warnings. It looks ok. I have noticed if I try to render only a button it is also unresponsive.

**Comment by scottpersinger** [comment]
Seeing the same thing - if you check the JS console there's a ton of errors. Seems like maybe the React code is out of date...

**Comment by haizibinbin** [comment]
I have the same problem, is this project still maintained?

**Comment by ddcroft73** [comment]
It is not maintained that I can tell, and it is out of date dependency Hell. This is one reason why frontend work drives me insane. Just as well to start from scratch with a good component library. Aside from this front end issue. I'm having issues in the back with celery, and flower connection refusals. Some of the app works, some doesn't. To be expected. I have since moved on and started my own project anyway picking some of these boilerplate templates apart, and using the docs. Its easier Im starting to see to just put the template together yourself.
