### ISSUE TITLE
Swagger docs not working out of the box at start of project

### ISSUE THREAD

**Issue by kingsleyliao** [Buuntu/fastapi-react#79]
Going to http://localhost:8000/api/docs has a routing issue in the path. I'm not familiar enough with the project to be able to diagnose the issue, but it seems like it should be a relatively simple fix for someone who knows the project.

![Screen Shot 2020-07-04 at 10 13 38 PM](https://user-images.githubusercontent.com/19790133/86524085-05a56380-be44-11ea-85b3-95917b2a2e49.png)

**Comment by Buuntu** [comment]
Good catch, I believe this had to do with a newer version of FastAPI changing how `root_path` works in the uvicorn configuration.  Should be fixed now.
