### ISSUE TITLE
[Feature Request] Add Storybook support

### ISSUE THREAD

**Issue by inactivist** [Buuntu/fastapi-react#86]
Any thoughts on adding [Storybook](https://storybook.js.org/) support as part of a development workflow?

**Comment by Buuntu** [comment]
I'll play around with this, honestly I haven't used it before. If you open a PR I would love to try it out.

**Comment by inactivist** [comment]
> I'll play around with this, honestly I haven't used it before. If you open a PR I would love to try it out.

I'll see what I can put together on my end

**Comment by Buuntu** [comment]
Closing this for now as it's not really a bug/issue but am open to PRs around this.
